name: CLI tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.5.3
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'sapmachine'
        java-version: '17'
    - name: Build
      run: mvn -B -ntp --file pom.xml -DskipTests package
      env:
        MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - name: Run CLI tests
      run: bash src/test/shell/tool/github/run_tests.sh
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #once this credential is available, this could allow for fast pipeline runs
        #NVD_API_KEAY: ${{ secrets.NVD_API_KEY }}
